server:
  log_level: warn
metrics:
  wal_directory: C:\ProgramData\grafana-agent-wal
  global:
    scrape_interval: 1m
  configs:
    - name: integrations
logs:
  # Choose a directory to save the last read position of log files at.
  # This directory will be created if it doesn't already exist.
  positions_directory: "C:\\Program Files\\Grafana Agent\\lastRead"
  configs:
    - name: ironwatch
      # Loki endpoint to push logs to
      clients:
        - url: http://3.89.162.169:3100/loki/api/v1/push
      scrape_configs:
      - job_name: TeleMed
        static_configs:
          - targets: [localhost]
            labels:
            __path__: "C:\\Program Files\\Grafana Agent\\logs\\*log"
integrations:
  windows_exporter:
    enabled: true