server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./positions.yaml

clients:
  - url: http://{IP_ADDRESS_OF_LOKI}/loki/api/v1/push

scrape_configs:
  - job_name: CallHistory
    pipeline_stages:
      - json:
          expressions:
            CallHistoryID: CallHistoryId
            Direction: Direction
            DisconnectCause: DisconnectCause
            DisconnectCauseType: DisconnectCauseType
            CallBackNumber: CallBackNumber
            DisplayName: CallerDisplayName
            Duration: Duration
            StartTime: StartTime
            EndTime: EndTime
            VideoUsed: VideoUsed
    static_configs:
    - targets:
        - localhost
      labels:
        job: CallHistory
        site: {location}
        __path__: C:\Users\Display2\logs\*_CallHistory.json
  - job_name: xStatus
    pipeline_stages:
      - json:
          expressions:
            Audio: Audio
            Cameras: Cameras
            Diagnostics: Diagnostics
            Network: Network
            SIP: SIP
            SystemUnit: SystemUnit
            Webex: Webex
            Video: Video
    static_configs:
    - targets:
        - localhost
      labels:
        job: xStatus
        site: {location}
        __path__: C:\Users\Display2\logs\*_xstatus.json
  - job_name: xConfiguration
    pipeline_stages:
      - json:
          expressions:
            Audio: Audio
            Cameras: Cameras
            Conference: Conference
            Network: Network
            NetworkServices: NetworkServices
            SIP: SIP
            Security: Security
            SystemUnit: SystemUnit
            Video: Video
    static_configs:
    - targets:
        - localhost
      labels:
        job: xConfiguration
        site: {location}
        __path__: C:\Users\Display2\logs\*_xConfiguration.json
