server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./positions.yaml

clients:
  - url: http://{IP_ADDRESS_OF_LOKI}/loki/api/v1/push

scrape_configs:
  - job_name: TeleMed
    static_configs:
    - targets:
        - localhost
      labels:
        job: ironwatch
        __path__: C:\Users\Display2\logs\*.json